version: '3.8'

services:
  wazuh-manager:
    image: wazuh/wazuh-manager:4.7.0
    container_name: wazuh-manager
    ports:
      - "1514:1514"
      - "1515:1515"
      - "55000:55000"
    volumes:
      - wazuh-manager-data:/var/ossec/data
      - wazuh-manager-logs:/var/ossec/logs
      - wazuh-manager-config:/var/ossec/etc
    environment:
      - WAZUH_MANAGER_PASSWORD=${WAZUH_MANAGER_PASSWORD:-ChangeMe123!}
    networks:
      - asoc-network

  wazuh-dashboard:
    image: wazuh/wazuh-dashboard:4.7.0
    container_name: wazuh-dashboard
    ports:
      - "443:443"
    volumes:
      - wazuh-dashboard-data:/usr/share/wazuh-dashboard/data
      - wazuh-dashboard-config:/usr/share/wazuh-dashboard/config
    environment:
      - WAZUH_API_URL=https://wazuh-manager:55000
      - WAZUH_API_USERNAME=admin
      - WAZUH_API_PASSWORD=${WAZUH_MANAGER_PASSWORD:-ChangeMe123!}
    depends_on:
      - wazuh-manager
    networks:
      - asoc-network

  mcp-platform:
    image: parthasarathi7722/mcp-platform:latest
    container_name: mcp-platform
    ports:
      - "8000:8000"
    volumes:
      - mcp-platform-data:/app/data
      - mcp-platform-logs:/app/logs
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - JWT_SECRET=${JWT_SECRET:-ChangeMe123!}
      - WAZUH_API_URL=https://wazuh-manager:55000
      - WAZUH_USERNAME=admin
      - WAZUH_PASSWORD=${WAZUH_MANAGER_PASSWORD:-ChangeMe123!}
    depends_on:
      - wazuh-manager
    networks:
      - asoc-network

  terraform:
    image: hashicorp/terraform:1.5.0
    container_name: terraform
    volumes:
      - ./terraform:/terraform
      - ~/.aws:/root/.aws:ro
    working_dir: /terraform
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
    networks:
      - asoc-network

volumes:
  wazuh-manager-data:
  wazuh-manager-logs:
  wazuh-manager-config:
  wazuh-dashboard-data:
  wazuh-dashboard-config:
  mcp-platform-data:
  mcp-platform-logs:

networks:
  asoc-network:
    driver: bridge 