apiVersion: v1
kind: ConfigMap
metadata:
  name: wazuh-config
  namespace: asoc-mcp
data:
  ossec.conf: |
    <ossec_config>
      <global>
        <jsonout_output>yes</jsonout_output>
        <alerts_log>yes</alerts_log>
        <logall>no</logall>
        <logall_json>no</logall_json>
        <email_notification>no</email_notification>
        <smtp_server>smtp.example.com</smtp_server>
        <smtp_port>587</smtp_port>
        <smtp_user>user@example.com</smtp_user>
        <smtp_password>password</smtp_password>
        <from>wazuh@example.com</from>
      </global>
      <integration>
        <name>mcp</name>
        <api_url>http://mcp-platform:8000/api/v1</api_url>
        <api_key>${MCP_API_KEY}</api_key>
      </integration>
    </ossec_config>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mcp-platform-config
  namespace: asoc-mcp
data:
  config.yaml: |
    api:
      host: 0.0.0.0
      port: 8000
      debug: false
    security:
      jwt_secret: ${JWT_SECRET}
    wazuh:
      api_url: https://wazuh-manager:55000
      username: admin
      password: ${WAZUH_MANAGER_PASSWORD}
    openai:
      api_key: ${OPENAI_API_KEY} 